### ISSUE TITLE
kitura init needs root access

### ISSUE THREAD

**Issue by Soryu** [IBM-Swift/kitura-cli#2]
`kitura init` is trying to install `generator-swiftserver` globally. Which I just did following https://github.com/ibm-swift/kitura-cli because it is an explicit dependency.

Would it make more sense to check if `generator-swiftserver` is available and exit with an error if it’s not?

**Comment by ianpartridge** [comment]
`generator-swiftserver` need to be installed as a global NPM module so that Yeoman can find it. By running the `npm i` when `kitura init` is invoked we can decouple the Kitura CLI from the version of the generator: if we release a new version of the generator the CLI will pick it up automatically without user intervention or having to upgrade the CLI as well.  That was my thinking, anyway!  Does it make sense?

**Comment by ianpartridge** [comment]
I don't think it's true that `kitura init` needs root access though - it just needs to access the global node module. I don't run the CLI as root.

**Comment by Soryu** [comment]
Sorry, this is probably bogus. I was running it on my Ubuntu 14.04 LTS server, there the global `node_module` was in `/usr/lib`. I realised I don’t need to run this on the server, so this is not an issue anymore. Thanks for the fast response!
