### ISSUE TITLE
Auto-scaling shows only memory

### ISSUE THREAD

**Issue by icyield** [IBM-Swift/kitura-cli#24]
Auto-Scaling does not generate any throughput or response metrics. 

To test a basic app with only autoscale will do. 
The /metrics route gives lots of data, but is not making connection to the auto-scale "agent". 
The metrics statics for Throughput and Response Time are N/A. 

Is there another route that autoscale uses to get this data?

**Comment by icyield** [comment]
Looking  at the SwiftEnterpriseDemo. They do init of SwiftMetricsBluemix differently.

I removed the   
// autoScalingService = try initializeServiceAutoscaling(cloudEnv: cloudEnv)
 In Application.swift and and instead added in Metrics.swift 

var bluemixMetrics : SwiftMetricsBluemix?
func initializeMetrics(app: App) {
    do {
        let metrics = try SwiftMetrics()
        bluemixMetrics = SwiftMetricsBluemix(swiftMetricsInstance: metrics)
        
And auto scale dials now work. Also I had explicitly bumped packages to from 2.1.

Not sure if the packages update or the removal of the try initializeServiceAutoscaling were actually required for the fix.

**Comment by seabaylea** [comment]
@tunniclm @nhardman  Is this a problem with the way autoscaling is added in `kitura create`?

**Comment by tunniclm** [comment]
Just checked this out and there's an order of execution bug in the generated code.
The metrics get initialized after the autoscaling service and so the autoscaling service will always fail (it should log a message).

This problem was introduced into https://github.com/IBM-Swift/generator-swiftserver relatively recently when the application was refactored. Autoscaling is the only service that uses the metrics, so should be the only one affected.

@nhardman Can you take a look at this? Also, I'm not sure how this slipped through testing so we should also check why this wasn't picked up.

**Comment by ianpartridge** [comment]
@nhardman @tunniclm thanks for taking a look - can you raise an issue against https://github.com/IBM-Swift/generator-swiftserver link it here and close this issue? Thanks.

**Comment by ianpartridge** [comment]
Tracked by https://github.com/IBM-Swift/generator-swiftserver/issues/432
